<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <Authors>Harol A. Reina</Authors>
    <Company>Seguros TúPrimero Ltda</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/AppCore/AppCore.csproj" />
  </ItemGroup>

</Project>