// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace App.Infrastructure.Data.CompiledModels.AppDbContextModel
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("94fb5a56-c17d-40ee-a83b-71a82eec7bee"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var employeDao = EmployeDaoEntityType.Create(this);

            EmployeDaoEntityType.CreateAnnotations(employeDao);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.2");
            AddAnnotation("Relational:DefaultSchema", "public");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
