<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>1591;IL2104;IL3053;IL3000;IL3002</NoWarn>

    <!-- Enable NativeAOT Compilation -->
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>false</InvariantGlobalization>
    <StripSymbols>false</StripSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppCore\AppCore.csproj" />
  </ItemGroup>

</Project>
