using System.Text.Json.Serialization;
using AppCore.Application.DTOs;
using AppCore.Application.Exceptions;
using AppCore.Application.Wrappers;
using AppCore.Domain.Common;
using AppCore.Domain.Entities.Integrators;
using Microsoft.AspNetCore.Mvc;

namespace AppCore.Application.Serialization;

/// <summary>
/// Test model for JSON serialization unit tests.
/// Public type required for AOT source generation compatibility.
/// </summary>
public class JsonTestModel {
    public int Id { get; set; }
    public string? Name { get; set; }
    public string? Email { get; set; }
    public bool IsActive { get; set; }
}

/// <summary>
/// AOT-compatible JSON serialization context for AppCore types.
/// This provides compile-time source generation for JSON serialization,
/// eliminating the need for runtime reflection in Native AOT scenarios.
/// </summary>
[JsonSerializable(typeof(Response<object>))]
[JsonSerializable(typeof(Response<string>))]
[JsonSerializable(typeof(Response<int>))]
[JsonSerializable(typeof(Response<long>))]
[JsonSerializable(typeof(Response<bool>))]
[JsonSerializable(typeof(Response<Guid>))]
[JsonSerializable(typeof(Response<DictionaryError>))]
[JsonSerializable(typeof(Response<PaginationDto<int>>))]
[JsonSerializable(typeof(HttpResponse<object>))]
[JsonSerializable(typeof(HttpResponse<string>))]
[JsonSerializable(typeof(HttpResponse<EmailRequest>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(MappingErrorResponse))]
[JsonSerializable(typeof(CustomErrorResponse))]
[JsonSerializable(typeof(PaginationResponse<object>))]
[JsonSerializable(typeof(PaginationDto<object>))]
[JsonSerializable(typeof(PaginationDto<string>))]
[JsonSerializable(typeof(PaginationDto<int>))]
[JsonSerializable(typeof(BaseEntity<int>))]
[JsonSerializable(typeof(BaseEntity<long>))]
[JsonSerializable(typeof(BaseEntity<string>))]
[JsonSerializable(typeof(AuditableEntity))]
[JsonSerializable(typeof(HttpAuditEntity))]
[JsonSerializable(typeof(AttachmentFile))]
[JsonSerializable(typeof(EmailRequest))]
[JsonSerializable(typeof(DictionaryError))]
[JsonSerializable(typeof(MessageLog))]
[JsonSerializable(typeof(ValidationProblemDetails))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DateOnly))]
[JsonSerializable(typeof(TimeOnly))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<DictionaryError>))]
[JsonSerializable(typeof(JsonTestModel))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = true,
    PropertyNameCaseInsensitive = true,
    GenerationMode = JsonSourceGenerationMode.Default)]
public partial class AppCoreJsonContext : JsonSerializerContext {
    // The Default property is auto-generated by the source generator
}
