<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Dapper.AOT</InterceptorsNamespaces>
    <Nullable>enable</Nullable>
    <Authors>Harol A. Reina</Authors>
    <Company>Seguros TúPrimero Ltda</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591;CS9270</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/App.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.AOT" Version="1.0.2" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

</Project>
